export const RoofTopFacilities = {
  "가스레인지/인덕션": false,
  "간이 무대": false,
  "건물 내 무료주차": false,
  "건물 내 화장실": false,
  "고층 (15층 이상)": false,
  "구급 기구": false,
  냉장고: false,
  "무료 와이파이": false,
  "몽골 천막": false,
  "바베큐 기기": false,
  "반려견 동반 가능": false,
  "빠르게 짐 맡기기": false,
  식기류: false,
  엘레베이터: false,
  오븐: false,
  "음향 / 마이크": false,
  "장애 편의시설": false,
  "저층 (5층 이하)": false,
  전자레인지: false,
  조리도구: false,
  "조리 불가": false,
  "주류 반입 가능": false,
  "주류 반입 불가": false,
  "취식 가능": false,
  "캐노피 천막": false,
  "테이블 / 의자": false,
  "프로젝터 / TV": false,
  해먹: false,
  "흡연 가능": false,
  "흡연 불가": false,
}
